import sys
from pathlib import Path

# Add backend directory to sys.path
backend_dir = Path(__file__).resolve().parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from app.supabase_client import supabase  # noqa: E402

SEED_DATASETS = [
    # ----------------------------------------------------
    # ELLA PILOT REGION (Badulla District, Uva Province)
    # ----------------------------------------------------
    {
        "id": 1,
        "name": "Ella Nine Arch Bridge & Demodara Viaduct",
        "title": "Ella Nine Arch Bridge & Demodara Viaduct",
        "category": "nature",
        "district": "Badulla",
        "province": "Uva",
        "latitude": 6.8768,
        "longitude": 81.0608,
        "description": "Iconic colonial viaduct tucked into dense tea hills, where blue mountain trains cross scenic jungle valleys.",
        "activities": [
            "Train Spotting",
            "Tea Plantation Walking",
            "Photography",
            "Hiking",
        ],
        "estimated_visit_duration_minutes": 180,
        "baseline_cost": 0.00,
        "popularity": 4.95,
        "rating": 4.95,
        "reviews": 890,
        "trust_score": 0.99,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "09:00 - 12:00",
            "peak_months": ["Dec", "Jan", "Feb", "Jul"],
        },
        "partner_info": {
            "name": "Ella Blue Train Photographers & Drivers Co-op",
            "type": "Tuk-Tuk & Guide Co-op",
            "contact": "+94 57 222 3410",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 2150, "save_count": 940},
        "nearby_attractions": [
            "Little Adam's Peak",
            "Ravana Falls & Cave",
            "Demodara Loop Secret Overlook",
        ],
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "52%",
        "coord_y": "48%",
        "elevation": "1,041 m",
        "distance_from_colombo": "200 km from Colombo",
    },
    {
        "id": 2,
        "name": "Ella Rock Peak & Cliff Trail",
        "title": "Ella Rock Peak & Cliff Trail",
        "category": "adventure",
        "district": "Badulla",
        "province": "Uva",
        "latitude": 6.8580,
        "longitude": 81.0470,
        "description": "Challenging mountain hike across railway tracks, eucalyptus forests, and tea gardens leading to sheer drop-off cliff vistas over Ella Gap.",
        "activities": [
            "Mountain Trekking",
            "Cliff Edge Viewpoints",
            "Photography",
        ],
        "estimated_visit_duration_minutes": 240,
        "baseline_cost": 0.00,
        "popularity": 4.88,
        "rating": 4.88,
        "reviews": 640,
        "trust_score": 0.97,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "06:30 - 10:00",
            "peak_months": ["Dec", "Jan", "Feb", "Aug"],
        },
        "partner_info": {
            "name": "Ella Trail Guides Association",
            "type": "Local Eco-Guide Association",
            "contact": "+94 77 345 6789",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 1420, "save_count": 680},
        "nearby_attractions": [
            "Ella Nine Arch Bridge",
            "Kital Ella Falls",
            "Ravana Cave",
        ],
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "53%",
        "coord_y": "49%",
        "elevation": "1,350 m",
        "distance_from_colombo": "202 km from Colombo",
    },
    {
        "id": 3,
        "name": "Little Adam's Peak (Punchi Sri Pada)",
        "title": "Little Adam's Peak",
        "category": "nature",
        "district": "Badulla",
        "province": "Uva",
        "latitude": 6.8624,
        "longitude": 81.0583,
        "description": "Accessible scenic staircase trail passing tea pickers leading to twin panoramic mountain summits overlooking southern plains.",
        "activities": [
            "Sunset Walking",
            "Tea Estate Tour",
            "Ziplining & Adventure",
        ],
        "estimated_visit_duration_minutes": 120,
        "baseline_cost": 0.00,
        "popularity": 4.90,
        "rating": 4.90,
        "reviews": 780,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "16:00 - 18:30",
            "peak_months": ["Dec", "Jan", "Feb", "Aug"],
        },
        "partner_info": {
            "name": "Flying Ravana Zipline & Adventure Hub",
            "type": "Certified Adventure Operator",
            "contact": "+94 57 205 0050",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 1890, "save_count": 810},
        "nearby_attractions": [
            "Ella Nine Arch Bridge",
            "Ravana Pool Club",
            "Ella Gap Vantage",
        ],
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "54%",
        "coord_y": "50%",
        "elevation": "1,141 m",
        "distance_from_colombo": "205 km from Colombo",
    },
    {
        "id": 4,
        "name": "Demodara Railway Loop & Secret Overlook",
        "title": "Demodara Railway Loop Secret Overlook",
        "category": "heritage",
        "district": "Badulla",
        "province": "Uva",
        "latitude": 6.8970,
        "longitude": 81.0660,
        "description": "Lesser-known engineering marvel where the train track loops around a mountain spiral and emerges directly beneath the station platform.",
        "activities": ["Engineering History", "Photography", "Train Watching"],
        "estimated_visit_duration_minutes": 90,
        "baseline_cost": 0.00,
        "popularity": 4.72,
        "rating": 4.72,
        "reviews": 120,
        "trust_score": 0.91,
        "verification_state": "community_submitted",
        "publication_status": "published",
        "is_verified": False,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "10:30 - 12:30",
            "peak_months": ["Dec", "Jan", "Feb"],
        },
        "partner_info": {
            "name": "Demodara Village Heritage Guild",
            "type": "Local Community Host",
            "contact": "+94 71 890 1234",
            "rating": 4.7,
            "verified": False,
        },
        "community_stats": {"upvotes": 340, "save_count": 180},
        "nearby_attractions": [
            "Ella Nine Arch Bridge",
            "Blackwood Tea Factory",
        ],
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "51%",
        "coord_y": "47%",
        "elevation": "912 m",
        "distance_from_colombo": "198 km from Colombo",
    },
    # ----------------------------------------------------
    # SIGIRIYA CORRIDOR (Matale District, Central Province)
    # ----------------------------------------------------
    {
        "id": 5,
        "name": "Sigiriya Ancient Rock Fortress",
        "title": "Sigiriya Ancient Rock Fortress",
        "category": "heritage",
        "district": "Matale",
        "province": "Central",
        "latitude": 7.9570,
        "longitude": 80.7600,
        "description": "5th-century royal citadel towering 200 meters over emerald jungle, famous for frescoes, mirror wall, and royal water gardens.",
        "activities": [
            "Rock Climbing",
            "History Tour",
            "Photography",
            "Archaeology",
        ],
        "estimated_visit_duration_minutes": 240,
        "baseline_cost": 36.00,
        "popularity": 4.95,
        "rating": 4.95,
        "reviews": 1240,
        "trust_score": 0.99,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "07:30 - 11:00",
            "peak_months": ["Dec", "Jan", "Aug"],
        },
        "partner_info": {
            "name": "Central Cultural Fund Licensed Guides",
            "type": "Official Heritage Guides",
            "contact": "+94 66 228 6540",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 3420, "save_count": 1540},
        "nearby_attractions": [
            "Pidurangala Rock Peak",
            "Dambulla Royal Cave Temple",
            "Kaludiya Pokuna",
        ],
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "28%",
        "coord_y": "22%",
        "elevation": "349 m",
        "distance_from_colombo": "165 km from Colombo",
    },
    {
        "id": 6,
        "name": "Pidurangala Rock Peak & Sunrise Overlook",
        "title": "Pidurangala Rock Peak",
        "category": "adventure",
        "district": "Matale",
        "province": "Central",
        "latitude": 7.9672,
        "longitude": 80.7681,
        "description": "Uncrowded mountain alternative right opposite Sigiriya offering unobstructed 360-degree sunrise vistas of the ancient citadel.",
        "activities": [
            "Dawn Rock Scramble",
            "Monastery Cave Ruins",
            "Sunrise Photography",
        ],
        "estimated_visit_duration_minutes": 150,
        "baseline_cost": 3.00,
        "popularity": 4.91,
        "rating": 4.91,
        "reviews": 680,
        "trust_score": 0.97,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "05:15 - 07:00",
            "peak_months": ["Dec", "Jan", "Feb", "Aug"],
        },
        "partner_info": {
            "name": "Pidurangala Temple Eco Trust",
            "type": "Monastery Heritage Trust",
            "contact": "+94 66 228 7100",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 1980, "save_count": 890},
        "nearby_attractions": [
            "Sigiriya Ancient Citadel",
            "Hiriwadunna Eco Tank",
        ],
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "29%",
        "coord_y": "21%",
        "elevation": "360 m",
        "distance_from_colombo": "167 km from Colombo",
    },
    {
        "id": 7,
        "name": "Dambulla Royal Cave Temple (Jambukola Viharaya)",
        "title": "Dambulla Royal Cave Temple",
        "category": "heritage",
        "district": "Matale",
        "province": "Central",
        "latitude": 7.8567,
        "longitude": 80.6483,
        "description": "Best preserved cave temple complex in Sri Lanka containing 153 Buddha statues and vibrant rock ceiling paintings dating to 1st century BCE.",
        "activities": [
            "Cave Exploration",
            "Buddhist Art Appreciation",
            "Panoramic Views",
        ],
        "estimated_visit_duration_minutes": 120,
        "baseline_cost": 10.00,
        "popularity": 4.86,
        "rating": 4.86,
        "reviews": 920,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "09:00 - 12:00",
            "peak_months": ["Dec", "Jan", "Jul", "Aug"],
        },
        "partner_info": {
            "name": "Dambulla Heritage Guild",
            "type": "Cultural Heritage Association",
            "contact": "+94 66 228 4720",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 2340, "save_count": 980},
        "nearby_attractions": [
            "Sigiriya Citadel",
            "Ibbankatuwa Megalithic Tombs",
        ],
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "30%",
        "coord_y": "25%",
        "elevation": "160 m",
        "distance_from_colombo": "148 km from Colombo",
    },
    {
        "id": 8,
        "name": "Kaludiya Pokuna Forest Monastery & Hermitage",
        "title": "Kaludiya Pokuna Forest Monastery",
        "category": "nature",
        "district": "Matale",
        "province": "Central",
        "latitude": 7.8631,
        "longitude": 80.7042,
        "description": "Hidden 9th-century forest monastery with black water reflections, ancient stone ruins, and tranquil jungle walking trails.",
        "activities": ["Forest Bathing", "Bird Watching", "Quiet Meditation"],
        "estimated_visit_duration_minutes": 150,
        "baseline_cost": 0.00,
        "popularity": 4.70,
        "rating": 4.70,
        "reviews": 85,
        "trust_score": 0.89,
        "verification_state": "community_submitted",
        "publication_status": "published",
        "is_verified": False,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "08:00 - 10:30",
            "peak_months": ["Jan", "Aug", "Sep"],
        },
        "partner_info": {
            "name": "Kandalama Eco Rangers",
            "type": "Eco-Ranger Volunteer Group",
            "contact": "+94 77 456 7890",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 290, "save_count": 140},
        "nearby_attractions": [
            "Kandalama Reservoir",
            "Sigiriya Rock Fortress",
        ],
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "31%",
        "coord_y": "24%",
        "elevation": "180 m",
        "distance_from_colombo": "152 km from Colombo",
    },
    # ----------------------------------------------------
    # GALLE & SOUTHERN COAST CORRIDOR
    # ----------------------------------------------------
    {
        "id": 9,
        "name": "Galle Dutch Fort & Heritage Ramparts",
        "title": "Galle Dutch Fort & Heritage Ramparts",
        "category": "heritage",
        "district": "Galle",
        "province": "Southern",
        "latitude": 6.0269,
        "longitude": 80.2170,
        "description": "UNESCO World Heritage 17th-century Dutch colonial fortification with cobblestone streets, lighthouse, and oceanfront ramparts.",
        "activities": [
            "Rampart Walking",
            "Architecture Tour",
            "Boutique Shopping",
            "Sunset Watching",
        ],
        "estimated_visit_duration_minutes": 210,
        "baseline_cost": 0.00,
        "popularity": 4.93,
        "rating": 4.93,
        "reviews": 1450,
        "trust_score": 0.99,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "16:00 - 19:00",
            "peak_months": ["Nov", "Dec", "Jan", "Feb"],
        },
        "partner_info": {
            "name": "Galle Fort Heritage Foundation",
            "type": "Heritage Preservation Society",
            "contact": "+94 91 223 4567",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 3890, "save_count": 1720},
        "nearby_attractions": [
            "Rumassala Sanctuary Trail",
            "Unawatuna Jungle Beach",
            "Koggala Lake",
        ],
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "68%",
        "coord_y": "78%",
        "elevation": "12 m",
        "distance_from_colombo": "125 km from Colombo",
    },
    {
        "id": 10,
        "name": "Mirissa Coconut Tree Hill & Secret Beach",
        "title": "Mirissa Coconut Tree Hill & Secret Beach",
        "category": "beach",
        "district": "Matara",
        "province": "Southern",
        "latitude": 5.9470,
        "longitude": 80.4578,
        "description": "Dramatic red-clay headland lined with coconut palms overlooking turquoise Indian Ocean waves and whale migration paths.",
        "activities": [
            "Whale Watching",
            "Surfing",
            "Sunset Watching",
            "Snorkeling",
        ],
        "estimated_visit_duration_minutes": 150,
        "baseline_cost": 15.00,
        "popularity": 4.89,
        "rating": 4.89,
        "reviews": 840,
        "trust_score": 0.96,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "16:30 - 18:30",
            "peak_months": ["Nov", "Dec", "Jan", "Mar"],
        },
        "partner_info": {
            "name": "Mirissa Eco Boatmen & Whale Conservation Guild",
            "type": "Marine Eco-Tour Operators",
            "contact": "+94 41 225 0980",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 1820, "save_count": 790},
        "nearby_attractions": [
            "Weligama Bay Surf Point",
            "Polhena Coral Reef",
            "Galle Fort",
        ],
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "70%",
        "coord_y": "75%",
        "elevation": "15 m",
        "distance_from_colombo": "150 km from Colombo",
    },
    {
        "id": 11,
        "name": "Rumassala Sanctuary Trail & Japanese Peace Pagoda",
        "title": "Rumassala Sanctuary Trail & Peace Pagoda",
        "category": "nature",
        "district": "Galle",
        "province": "Southern",
        "latitude": 6.0125,
        "longitude": 80.2450,
        "description": "Mythological coastal mountain biodiversity hotspot overlooking Galle Harbor, featuring jungle medicinal plant paths and white stupa.",
        "activities": [
            "Medicinal Plant Trail",
            "Snorkeling at Jungle Beach",
            "Harbor Vistas",
        ],
        "estimated_visit_duration_minutes": 150,
        "baseline_cost": 0.00,
        "popularity": 4.78,
        "rating": 4.78,
        "reviews": 210,
        "trust_score": 0.93,
        "verification_state": "community_submitted",
        "publication_status": "published",
        "is_verified": False,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "15:30 - 18:00",
            "peak_months": ["Dec", "Jan", "Feb"],
        },
        "partner_info": {
            "name": "Unawatuna Eco Boatmen Co-op",
            "type": "Snorkeling & Boat Co-op",
            "contact": "+94 91 567 8901",
            "rating": 4.7,
            "verified": True,
        },
        "community_stats": {"upvotes": 580, "save_count": 290},
        "nearby_attractions": [
            "Galle Fort",
            "Unawatuna Bay",
        ],
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "69%",
        "coord_y": "77%",
        "elevation": "70 m",
        "distance_from_colombo": "122 km from Colombo",
    },
    {
        "id": 12,
        "name": "Yala National Park Safari Reserve",
        "title": "Yala National Park Safari",
        "category": "wildlife",
        "district": "Hambantota",
        "province": "Southern",
        "latitude": 6.3725,
        "longitude": 81.5165,
        "description": "World famous leopard habitat with dense jungle lagoons, sloth bears, and wild Asian elephant herds.",
        "activities": [
            "Jeep Safari",
            "Wildlife Photography",
            "Bird Watching",
        ],
        "estimated_visit_duration_minutes": 300,
        "baseline_cost": 45.00,
        "popularity": 4.92,
        "rating": 4.92,
        "reviews": 1120,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "06:00 - 09:00",
            "peak_months": ["Feb", "Mar", "Apr", "Jul"],
        },
        "partner_info": {
            "name": "Yala Safari Drivers & Wildlife Trackers Co-op",
            "type": "Certified Jeep Safari Drivers",
            "contact": "+94 47 223 9010",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 2890, "save_count": 1210},
        "nearby_attractions": [
            "Kirinda Beach Temple",
            "Bundala Wetland Sanctuary",
        ],
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "65%",
        "coord_y": "80%",
        "elevation": "30 m",
        "distance_from_colombo": "290 km from Colombo",
    },
    # ----------------------------------------------------
    # KANDY & HILL COUNTRY CORRIDOR
    # ----------------------------------------------------
    {
        "id": 13,
        "name": "Temple of the Sacred Tooth Relic (Sri Dalada Maligawa)",
        "title": "Temple of the Sacred Tooth Relic",
        "category": "temple",
        "district": "Kandy",
        "province": "Central",
        "latitude": 7.2936,
        "longitude": 80.6413,
        "description": "Sacred Buddhist shrine in Royal Palace complex holding the tooth relic of the Buddha, overlooking historic Kandy Lake.",
        "activities": [
            "Cultural Worship",
            "Museum Tour",
            "Heritage Exploration",
        ],
        "estimated_visit_duration_minutes": 150,
        "baseline_cost": 15.00,
        "popularity": 4.91,
        "rating": 4.91,
        "reviews": 1580,
        "trust_score": 0.99,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "09:30 - 11:30",
            "peak_months": ["Jul", "Aug", "Dec"],
        },
        "partner_info": {
            "name": "Kandy Royal Heritage Guides",
            "type": "Licensed Cultural Guides",
            "contact": "+94 81 223 4321",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 4120, "save_count": 1850},
        "nearby_attractions": [
            "Udawatta Kele Forest Sanctuary",
            "Royal Botanical Gardens Peradeniya",
            "Hanthana Mountain",
        ],
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "40%",
        "coord_y": "38%",
        "elevation": "500 m",
        "distance_from_colombo": "115 km from Colombo",
    },
    {
        "id": 14,
        "name": "Udawatta Kele Sanctuary & Royal Forest Reserve",
        "title": "Udawatta Kele Sanctuary",
        "category": "nature",
        "district": "Kandy",
        "province": "Central",
        "latitude": 7.2990,
        "longitude": 80.6425,
        "description": "Historic forest sanctuary directly behind the Tooth Temple, featuring ancient canopy trees, endemic lianas, and Buddhist forest hermitage caves.",
        "activities": ["Nature Trail Walking", "Bird Watching", "Photography"],
        "estimated_visit_duration_minutes": 120,
        "baseline_cost": 5.00,
        "popularity": 4.76,
        "rating": 4.76,
        "reviews": 160,
        "trust_score": 0.94,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "07:00 - 10:00",
            "peak_months": ["Jan", "Aug", "Dec"],
        },
        "partner_info": {
            "name": "Kandy Wildlife Rangers Guild",
            "type": "Eco-Ranger Organization",
            "contact": "+94 81 220 1234",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 490, "save_count": 220},
        "nearby_attractions": [
            "Temple of Tooth Relic",
            "Kandy Lake Walk",
        ],
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "41%",
        "coord_y": "37%",
        "elevation": "560 m",
        "distance_from_colombo": "116 km from Colombo",
    },
    {
        "id": 15,
        "name": "Ambuluwawa Biodiversity Complex & Tower",
        "title": "Ambuluwawa Biodiversity Tower",
        "category": "adventure",
        "district": "Gampola",
        "province": "Central",
        "latitude": 7.1611,
        "longitude": 80.5517,
        "description": "Unique multi-religious sanctuary featuring a breathtaking 48m white spiral tower perched atop a 3,300ft mountain peak.",
        "activities": [
            "Spiral Tower Ascent",
            "360-Degree Mountain Vistas",
            "Photography",
        ],
        "estimated_visit_duration_minutes": 180,
        "baseline_cost": 6.00,
        "popularity": 4.90,
        "rating": 4.90,
        "reviews": 710,
        "trust_score": 0.96,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "08:30 - 11:30",
            "peak_months": ["Dec", "Jan", "Feb", "Aug"],
        },
        "partner_info": {
            "name": "Gampola Mountain Tuk-Tuk Drivers Association",
            "type": "Mountain Transport Co-op",
            "contact": "+94 81 567 2345",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 1780, "save_count": 760},
        "nearby_attractions": [
            "Temple of Tooth Relic",
            "Gadaladeniya Temple",
        ],
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "43%",
        "coord_y": "42%",
        "elevation": "1,065 m",
        "distance_from_colombo": "105 km from Colombo",
    },
    {
        "id": 16,
        "name": "Horton Plains & World's End Precipice",
        "title": "Horton Plains & World's End Precipice",
        "category": "nature",
        "district": "Nuwara Eliya",
        "province": "Central",
        "latitude": 6.8028,
        "longitude": 80.8091,
        "description": "High-altitude montane cloud forest plateau featuring a sheer 880m vertical drop cliff at World's End and Baker's Falls.",
        "activities": [
            "Trekking",
            "Endemic Wildlife Watching",
            "Landscape Photography",
        ],
        "estimated_visit_duration_minutes": 240,
        "baseline_cost": 25.00,
        "popularity": 4.88,
        "rating": 4.88,
        "reviews": 560,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "06:00 - 09:00",
            "peak_months": ["Jan", "Feb", "Mar", "Aug"],
        },
        "partner_info": {
            "name": "Nuwara Eliya High Peak Guides",
            "type": "Trekking Guides Association",
            "contact": "+94 52 222 3890",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 1650, "save_count": 710},
        "nearby_attractions": [
            "Baker's Falls",
            "Pattipola Cloud Forest",
        ],
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "46%",
        "coord_y": "45%",
        "elevation": "2,100 m",
        "distance_from_colombo": "180 km from Colombo",
    },
    # ----------------------------------------------------
    # NORTHERN & EASTERN PILOT CORRIDOR
    # ----------------------------------------------------
    {
        "id": 17,
        "name": "Jaffna Nallur Kandaswamy Kovil & Dutch Fort",
        "title": "Jaffna Nallur Kovil & Dutch Fort",
        "category": "culture",
        "district": "Jaffna",
        "province": "Northern",
        "latitude": 9.6745,
        "longitude": 80.0298,
        "description": "Golden Dravidian Hindu temple complex famous for annual chariot festivals alongside star-shaped 17th-century coastal Dutch fort ruins.",
        "activities": [
            "Cultural Heritage Tour",
            "Temple Ceremony",
            "Lagoon Exploration",
        ],
        "estimated_visit_duration_minutes": 180,
        "baseline_cost": 0.00,
        "popularity": 4.82,
        "rating": 4.82,
        "reviews": 340,
        "trust_score": 0.97,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "07:00 - 10:00",
            "peak_months": ["Aug", "Sep", "Dec"],
        },
        "partner_info": {
            "name": "Northern Cultural Heritage Guides Co-op",
            "type": "Heritage Tour Co-op",
            "contact": "+94 21 222 5678",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 920, "save_count": 410},
        "nearby_attractions": [
            "Keerimalai Sacred Springs",
            "Nagadeepa Temple",
            "Delft Island",
        ],
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "10%",
        "coord_y": "15%",
        "elevation": "8 m",
        "distance_from_colombo": "395 km from Colombo",
    },
    {
        "id": 18,
        "name": "Keerimalai Sacred Springs & Ancient Tanks",
        "title": "Keerimalai Sacred Water Springs",
        "category": "heritage",
        "district": "Jaffna",
        "province": "Northern",
        "latitude": 9.8130,
        "longitude": 79.9530,
        "description": "Natural thermal spring bath complex directly beside Palk Strait ocean waves, famed for mineral therapeutic waters since antiquity.",
        "activities": [
            "Mineral Bathing",
            "Coastal Sunset Walk",
            "Temple Heritage",
        ],
        "estimated_visit_duration_minutes": 90,
        "baseline_cost": 0.00,
        "popularity": 4.74,
        "rating": 4.74,
        "reviews": 95,
        "trust_score": 0.91,
        "verification_state": "community_submitted",
        "publication_status": "published",
        "is_verified": False,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "16:00 - 18:30",
            "peak_months": ["Jul", "Aug", "Dec"],
        },
        "partner_info": {
            "name": "Jaffna Coast Drivers & Community Host",
            "type": "Local Community Host",
            "contact": "+94 77 901 2345",
            "rating": 4.7,
            "verified": False,
        },
        "community_stats": {"upvotes": 310, "save_count": 140},
        "nearby_attractions": [
            "Jaffna Nallur Kovil",
            "Dambakola Patuna",
        ],
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "9%",
        "coord_y": "12%",
        "elevation": "3 m",
        "distance_from_colombo": "405 km from Colombo",
    },
    {
        "id": 19,
        "name": "Nilaveli Beach & Pigeon Island Marine National Park",
        "title": "Nilaveli Beach & Pigeon Island",
        "category": "beach",
        "district": "Trincomalee",
        "province": "Eastern",
        "latitude": 8.6946,
        "longitude": 81.1983,
        "description": "Pristine white coastline and coral reef marine national park teeming with blacktip reef sharks, sea turtles, and coral fish.",
        "activities": [
            "Snorkeling",
            "Scuba Diving",
            "Boat Tour",
            "Beach Relaxing",
        ],
        "estimated_visit_duration_minutes": 210,
        "baseline_cost": 20.00,
        "popularity": 4.84,
        "rating": 4.84,
        "reviews": 420,
        "trust_score": 0.96,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "08:30 - 11:30",
            "peak_months": ["May", "Jun", "Jul", "Aug", "Sep"],
        },
        "partner_info": {
            "name": "Trincomalee Certified Marine Snorkel Operators",
            "type": "Certified Boat & Dive Co-op",
            "contact": "+94 26 222 7890",
            "rating": 4.9,
            "verified": True,
        },
        "community_stats": {"upvotes": 1240, "save_count": 520},
        "nearby_attractions": [
            "Koneswaram Temple",
            "Marble Beach",
        ],
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "20%",
        "coord_y": "70%",
        "elevation": "5 m",
        "distance_from_colombo": "270 km from Colombo",
    },
    {
        "id": 20,
        "name": "Delft Island Baobab Tree & Wild Horses Trail",
        "title": "Delft Island Wild Horses Trail",
        "category": "nature",
        "district": "Jaffna",
        "province": "Northern",
        "latitude": 9.5160,
        "longitude": 79.6830,
        "description": "Remote coral island in Palk Strait where wild ponies roam free among Portuguese/Dutch coral stone walls and 700-year-old Baobab tree.",
        "activities": [
            "Ferry Crossing",
            "Wild Horse Spotting",
            "Coral Wall History",
        ],
        "estimated_visit_duration_minutes": 360,
        "baseline_cost": 8.00,
        "popularity": 4.79,
        "rating": 4.79,
        "reviews": 115,
        "trust_score": 0.92,
        "verification_state": "community_submitted",
        "publication_status": "published",
        "is_verified": False,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "10:00 - 14:00",
            "peak_months": ["Jul", "Aug", "Sep"],
        },
        "partner_info": {
            "name": "Delft Island Local Boatmen & Guide Guild",
            "type": "Island Eco-Guide Co-op",
            "contact": "+94 77 678 9012",
            "rating": 4.8,
            "verified": True,
        },
        "community_stats": {"upvotes": 410, "save_count": 210},
        "nearby_attractions": [
            "Kurikadduwan Jetty",
            "Nagadeepa Purana Viharaya",
        ],
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "8%",
        "coord_y": "10%",
        "elevation": "4 m",
        "distance_from_colombo": "420 km from Colombo",
    },
]


def seed_database():
    """Seeds the authoritative Sri Lankan tourism destination database with rich pilot ecosystem records."""
    print(
        f"Starting seed pipeline with {len(SEED_DATASETS)} pilot destination records..."
    )

    if supabase:
        try:
            res = supabase.table("destinations").upsert(SEED_DATASETS).execute()
            print(
                f"[LankaLens Supabase Seed] Successfully upserted {len(res.data or [])} destinations!"
            )
            return res.data
        except Exception as e:
            print(f"[LankaLens Supabase Seed Warning] Supabase upsert error: {e}")

    print(
        "[LankaLens Seed] Database seed pipeline prepared in-memory dataset successfully."
    )
    return SEED_DATASETS


if __name__ == "__main__":
    seed_database()
