import sys
from pathlib import Path

# Add backend directory to sys.path
backend_dir = Path(__file__).resolve().parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from app.supabase_client import supabase  # noqa: E402

SEED_DATASETS = [
    {
        "id": 1,
        "name": "Sigiriya Ancient Rock Fortress",
        "title": "Sigiriya Ancient Rock Fortress",
        "category": "temple",
        "district": "Matale",
        "province": "Central",
        "latitude": 7.9570,
        "longitude": 80.7600,
        "description": "5th-century royal citadel towering 200 meters over emerald jungle, famous for frescoes, mirror wall, and royal water gardens.",
        "activities": ["Rock Climbing", "History Tour", "Photography", "Archaeology"],
        "estimated_visit_duration_minutes": 240,
        "baseline_cost": 36.00,
        "popularity": 4.90,
        "rating": 4.90,
        "reviews": 320,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "08:00 - 11:00",
            "peak_months": ["Dec", "Jan", "Aug"],
        },
        "community_stats": {"upvotes": 1280, "save_count": 540},
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "28%",
        "coord_y": "22%",
        "elevation": "349 m",
        "distance_from_colombo": "165 km from Colombo",
    },
    {
        "id": 2,
        "name": "Ella Nine Arch Bridge & Demodara",
        "title": "Ella Nine Arch Bridge & Demodara",
        "category": "nature",
        "district": "Badulla",
        "province": "Uva",
        "latitude": 6.8768,
        "longitude": 81.0608,
        "description": "Iconic colonial viaduct tucked into dense tea hills, where blue mountain trains cross scenic jungle valleys.",
        "activities": [
            "Train Spotting",
            "Tea Plantation Walking",
            "Photography",
            "Hiking",
        ],
        "estimated_visit_duration_minutes": 180,
        "baseline_cost": 0.00,
        "popularity": 4.90,
        "rating": 4.90,
        "reviews": 512,
        "trust_score": 0.96,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "09:00 - 12:00",
            "peak_months": ["Dec", "Jan", "Feb", "Jul"],
        },
        "community_stats": {"upvotes": 1890, "save_count": 820},
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "52%",
        "coord_y": "48%",
        "elevation": "1,041 m",
        "distance_from_colombo": "200 km from Colombo",
    },
    {
        "id": 3,
        "name": "Mirissa Coconut Tree Hill & Secret Beach",
        "title": "Mirissa Coconut Tree Hill & Secret Beach",
        "category": "beach",
        "district": "Matara",
        "province": "Southern",
        "latitude": 5.9470,
        "longitude": 80.4578,
        "description": "Dramatic red-clay headland lined with coconut palms overlooking turquoise Indian Ocean waves and whale migration paths.",
        "activities": ["Whale Watching", "Surfing", "Sunset Watching", "Snorkeling"],
        "estimated_visit_duration_minutes": 150,
        "baseline_cost": 15.00,
        "popularity": 4.80,
        "rating": 4.80,
        "reviews": 240,
        "trust_score": 0.94,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "16:30 - 18:30",
            "peak_months": ["Nov", "Dec", "Jan", "Mar"],
        },
        "community_stats": {"upvotes": 950, "save_count": 410},
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "70%",
        "coord_y": "75%",
        "elevation": "15 m",
        "distance_from_colombo": "150 km from Colombo",
    },
    {
        "id": 4,
        "name": "Yala National Park Safari",
        "title": "Yala National Park Safari",
        "category": "wildlife",
        "district": "Hambantota",
        "province": "Southern",
        "latitude": 6.3725,
        "longitude": 81.5165,
        "description": "World famous leopard habitat featuring dense jungle lagoons, sloth bears, and herds of wild Asian elephants.",
        "activities": ["Jeep Safari", "Wildlife Photography", "Bird Watching"],
        "estimated_visit_duration_minutes": 300,
        "baseline_cost": 45.00,
        "popularity": 4.90,
        "rating": 4.90,
        "reviews": 410,
        "trust_score": 0.97,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "06:00 - 09:00",
            "peak_months": ["Feb", "Mar", "Apr", "Jul"],
        },
        "community_stats": {"upvotes": 1420, "save_count": 670},
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "65%",
        "coord_y": "80%",
        "elevation": "30 m",
        "distance_from_colombo": "290 km from Colombo",
    },
    {
        "id": 5,
        "name": "Temple of the Sacred Tooth Relic (Sri Dalada Maligawa)",
        "title": "Temple of the Sacred Tooth Relic",
        "category": "temple",
        "district": "Kandy",
        "province": "Central",
        "latitude": 7.2936,
        "longitude": 80.6413,
        "description": "Sacred Buddhist shrine in the Royal Palace complex holding the relic of the tooth of the Buddha, overlooking Kandy Lake.",
        "activities": ["Cultural Worship", "Museum Tour", "Heritage Exploration"],
        "estimated_visit_duration_minutes": 150,
        "baseline_cost": 15.00,
        "popularity": 4.85,
        "rating": 4.85,
        "reviews": 680,
        "trust_score": 0.99,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "09:30 - 11:30",
            "peak_months": ["Jul", "Aug", "Dec"],
        },
        "community_stats": {"upvotes": 2100, "save_count": 910},
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "40%",
        "coord_y": "38%",
        "elevation": "500 m",
        "distance_from_colombo": "115 km from Colombo",
    },
    {
        "id": 6,
        "name": "Galle Dutch Fort & Heritage Ramparts",
        "title": "Galle Dutch Fort & Heritage Ramparts",
        "category": "heritage",
        "district": "Galle",
        "province": "Southern",
        "latitude": 6.0269,
        "longitude": 80.2170,
        "description": "UNESCO World Heritage 17th-century Dutch colonial fortification with cobblestone streets, lighthouse, and oceanfront ramparts.",
        "activities": [
            "Rampart Walking",
            "Architecture Tour",
            "Boutique Shopping",
            "Sunset Watching",
        ],
        "estimated_visit_duration_minutes": 210,
        "baseline_cost": 0.00,
        "popularity": 4.90,
        "rating": 4.90,
        "reviews": 730,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "16:00 - 19:00",
            "peak_months": ["Nov", "Dec", "Jan", "Feb"],
        },
        "community_stats": {"upvotes": 2450, "save_count": 1050},
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "68%",
        "coord_y": "78%",
        "elevation": "12 m",
        "distance_from_colombo": "125 km from Colombo",
    },
    {
        "id": 7,
        "name": "Adam's Peak Sacred Summit (Sri Pada)",
        "title": "Adam's Peak Sacred Summit (Sri Pada)",
        "category": "nature",
        "district": "Ratnapura",
        "province": "Sabaragamuwa",
        "latitude": 6.8096,
        "longitude": 80.4994,
        "description": "2,243m conical sacred mountain revered by four major religions, famous for midnight stair climbs and dramatic sunrise shadow phenomena.",
        "activities": ["Night Trekking", "Pilgrimage", "Sunrise Photography"],
        "estimated_visit_duration_minutes": 420,
        "baseline_cost": 0.00,
        "popularity": 4.88,
        "rating": 4.88,
        "reviews": 390,
        "trust_score": 0.97,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Very High",
            "peak_hours": "02:00 - 06:30",
            "peak_months": ["Dec", "Jan", "Feb", "Mar", "Apr"],
        },
        "community_stats": {"upvotes": 1670, "save_count": 780},
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "48%",
        "coord_y": "52%",
        "elevation": "2,243 m",
        "distance_from_colombo": "140 km from Colombo",
    },
    {
        "id": 8,
        "name": "Polonnaruwa Ancient Royal City",
        "title": "Polonnaruwa Ancient Royal City",
        "category": "heritage",
        "district": "Polonnaruwa",
        "province": "North Central",
        "latitude": 7.9403,
        "longitude": 81.0188,
        "description": "Medieval capital of Sri Lanka preserving colossal stone Buddha statues at Gal Vihara, ancient palaces, and vast reservoir engineering.",
        "activities": ["Bicycle Tour", "Archaeology", "History Exploration"],
        "estimated_visit_duration_minutes": 240,
        "baseline_cost": 30.00,
        "popularity": 4.82,
        "rating": 4.82,
        "reviews": 290,
        "trust_score": 0.97,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "08:00 - 11:00",
            "peak_months": ["Jul", "Aug", "Dec"],
        },
        "community_stats": {"upvotes": 890, "save_count": 340},
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "32%",
        "coord_y": "30%",
        "elevation": "60 m",
        "distance_from_colombo": "215 km from Colombo",
    },
    {
        "id": 9,
        "name": "Horton Plains & World's End Precipice",
        "title": "Horton Plains & World's End Precipice",
        "category": "nature",
        "district": "Nuwara Eliya",
        "province": "Central",
        "latitude": 6.8028,
        "longitude": 80.8091,
        "description": "High-altitude montane cloud forest plateau featuring a sheer 880m vertical drop cliff at World's End and Baker's Falls.",
        "activities": [
            "Trekking",
            "Endemic Wildlife Watching",
            "Landscape Photography",
        ],
        "estimated_visit_duration_minutes": 240,
        "baseline_cost": 25.00,
        "popularity": 4.86,
        "rating": 4.86,
        "reviews": 340,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "06:00 - 09:00",
            "peak_months": ["Jan", "Feb", "Mar", "Aug"],
        },
        "community_stats": {"upvotes": 1120, "save_count": 490},
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "46%",
        "coord_y": "45%",
        "elevation": "2,100 m",
        "distance_from_colombo": "180 km from Colombo",
    },
    {
        "id": 10,
        "name": "Nilaveli Beach & Pigeon Island National Park",
        "title": "Nilaveli Beach & Pigeon Island National Park",
        "category": "beach",
        "district": "Trincomalee",
        "province": "Eastern",
        "latitude": 8.6946,
        "longitude": 81.1983,
        "description": "Pristine white sand coastline and live coral reef marine park teeming with blacktip reef sharks and sea turtles.",
        "activities": ["Snorkeling", "Scuba Diving", "Boat Tour", "Beach Relaxing"],
        "estimated_visit_duration_minutes": 210,
        "baseline_cost": 20.00,
        "popularity": 4.78,
        "rating": 4.78,
        "reviews": 210,
        "trust_score": 0.95,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "08:30 - 11:30",
            "peak_months": ["May", "Jun", "Jul", "Aug", "Sep"],
        },
        "community_stats": {"upvotes": 780, "save_count": 310},
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "20%",
        "coord_y": "70%",
        "elevation": "5 m",
        "distance_from_colombo": "270 km from Colombo",
    },
    {
        "id": 11,
        "name": "Jaffna Nallur Kandaswamy Kovil & Jaffna Fort",
        "title": "Jaffna Nallur Kandaswamy Kovil & Fort",
        "category": "culture",
        "district": "Jaffna",
        "province": "Northern",
        "latitude": 9.6745,
        "longitude": 80.0298,
        "description": "Golden Dravidian Hindu temple complex famous for chariot festivals alongside 17th-century star-shaped Dutch fort ruins on Jaffna Lagoon.",
        "activities": [
            "Cultural Heritage Tour",
            "Temple Ceremony",
            "Lagoon Exploration",
        ],
        "estimated_visit_duration_minutes": 180,
        "baseline_cost": 0.00,
        "popularity": 4.80,
        "rating": 4.80,
        "reviews": 190,
        "trust_score": 0.96,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Moderate",
            "peak_hours": "07:00 - 10:00",
            "peak_months": ["Aug", "Sep", "Dec"],
        },
        "community_stats": {"upvotes": 640, "save_count": 270},
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "10%",
        "coord_y": "15%",
        "elevation": "8 m",
        "distance_from_colombo": "395 km from Colombo",
    },
    {
        "id": 12,
        "name": "Dambulla Royal Cave Temple",
        "title": "Dambulla Royal Cave Temple",
        "category": "heritage",
        "district": "Matale",
        "province": "Central",
        "latitude": 7.8567,
        "longitude": 80.6483,
        "description": "Best preserved cave temple complex in Sri Lanka containing 153 Buddha statues and vibrant rock ceiling paintings dating to 1st century BCE.",
        "activities": [
            "Cave Exploration",
            "Buddhist Art Appreciation",
            "Panoramic Views",
        ],
        "estimated_visit_duration_minutes": 120,
        "baseline_cost": 10.00,
        "popularity": 4.84,
        "rating": 4.84,
        "reviews": 460,
        "trust_score": 0.98,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "High",
            "peak_hours": "09:00 - 12:00",
            "peak_months": ["Dec", "Jan", "Jul", "Aug"],
        },
        "community_stats": {"upvotes": 1340, "save_count": 580},
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "30%",
        "coord_y": "25%",
        "elevation": "160 m",
        "distance_from_colombo": "148 km from Colombo",
    },
    {
        "id": 13,
        "name": "Sinharaja Rainforest Biosphere Reserve",
        "title": "Sinharaja Rainforest Biosphere Reserve",
        "category": "nature",
        "district": "Ratnapura",
        "province": "Sabaragamuwa",
        "latitude": 6.4056,
        "longitude": 80.4583,
        "description": "Primary lowland tropical rainforest and UNESCO World Heritage reserve home to 60%+ endemic flora, birds, and amphibians.",
        "activities": ["Jungle Trekking", "Bird Watching", "Eco Education"],
        "estimated_visit_duration_minutes": 300,
        "baseline_cost": 18.00,
        "popularity": 4.81,
        "rating": 4.81,
        "reviews": 175,
        "trust_score": 0.97,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "07:00 - 11:00",
            "peak_months": ["Dec", "Jan", "Feb", "Aug"],
        },
        "community_stats": {"upvotes": 720, "save_count": 390},
        "images": ["/stitch_images/sustainability.png"],
        "image_url": "/stitch_images/sustainability.png",
        "coord_x": "58%",
        "coord_y": "62%",
        "elevation": "300 m",
        "distance_from_colombo": "120 km from Colombo",
    },
    {
        "id": 14,
        "name": "Wilpattu National Park & Natural Villus",
        "title": "Wilpattu National Park & Natural Villus",
        "category": "wildlife",
        "district": "Puttalam",
        "province": "Northwestern",
        "latitude": 8.4552,
        "longitude": 80.0543,
        "description": "Sri Lanka's largest national park famous for natural rain-fed basin lakes (villus), leopards, sloth bears, and archaeological ruins.",
        "activities": ["Jeep Safari", "Nature Photography", "Bird Watching"],
        "estimated_visit_duration_minutes": 360,
        "baseline_cost": 40.00,
        "popularity": 4.79,
        "rating": 4.79,
        "reviews": 230,
        "trust_score": 0.96,
        "verification_state": "verified",
        "publication_status": "published",
        "is_verified": True,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "06:00 - 09:30",
            "peak_months": ["Feb", "Mar", "May", "Sep"],
        },
        "community_stats": {"upvotes": 810, "save_count": 360},
        "images": ["/stitch_images/map.png"],
        "image_url": "/stitch_images/map.png",
        "coord_x": "22%",
        "coord_y": "18%",
        "elevation": "45 m",
        "distance_from_colombo": "180 km from Colombo",
    },
    {
        "id": 15,
        "name": "Little Adam's Peak Secret Sunrise Ridge",
        "title": "Little Adam's Peak Secret Sunrise Ridge",
        "category": "adventure",
        "district": "Badulla",
        "province": "Uva",
        "latitude": 6.8624,
        "longitude": 81.0583,
        "description": "Crowdsourced off-trail vantage point 400m past main summit offering uninterrupted 360-degree views of Ella Gap at dawn.",
        "activities": ["Hiking", "Sunrise Watching", "Trail Exploration"],
        "estimated_visit_duration_minutes": 120,
        "baseline_cost": 0.00,
        "popularity": 4.75,
        "rating": 4.75,
        "reviews": 48,
        "trust_score": 0.82,
        "verification_state": "community_submitted",
        "publication_status": "published",
        "is_verified": False,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "05:30 - 07:00",
            "peak_months": ["Dec", "Jan", "Feb"],
        },
        "community_stats": {"upvotes": 248, "save_count": 115},
        "images": ["/stitch_images/planner.png"],
        "image_url": "/stitch_images/planner.png",
        "coord_x": "54%",
        "coord_y": "50%",
        "elevation": "1,141 m",
        "distance_from_colombo": "205 km from Colombo",
    },
    {
        "id": 16,
        "name": "Kumbuk River Eco Hideaway & Elephant Treehouse",
        "title": "Kumbuk River Eco Hideaway",
        "category": "nature",
        "district": "Monaragala",
        "province": "Uva",
        "latitude": 6.7580,
        "longitude": 81.3320,
        "description": "Secluded eco resort and conservation spot nestled on riverbanks featuring giant elephant-shaped wooden architecture.",
        "activities": ["Eco Lodging", "River Swimming", "Stargazing"],
        "estimated_visit_duration_minutes": 240,
        "baseline_cost": 25.00,
        "popularity": 4.70,
        "rating": 4.70,
        "reviews": 34,
        "trust_score": 0.80,
        "verification_state": "community_submitted",
        "publication_status": "published",
        "is_verified": False,
        "crowd_info": {
            "density": "Low",
            "peak_hours": "14:00 - 18:00",
            "peak_months": ["Jan", "Aug", "Sep"],
        },
        "community_stats": {"upvotes": 184, "save_count": 92},
        "images": ["/stitch_images/discover.png"],
        "image_url": "/stitch_images/discover.png",
        "coord_x": "60%",
        "coord_y": "65%",
        "elevation": "120 m",
        "distance_from_colombo": "240 km from Colombo",
    },
]


def seed_database():
    """Seeds the authoritative Sri Lankan tourism destination database."""
    print(f"Starting seed pipeline with {len(SEED_DATASETS)} destination records...")

    if supabase:
        try:
            # Check existing destinations
            res = supabase.table("destinations").upsert(SEED_DATASETS).execute()
            print(
                f"[LankaLens Supabase Seed] Successfully upserted {len(res.data or [])} destinations!"
            )
            return res.data
        except Exception as e:
            print(f"[LankaLens Supabase Seed Warning] Supabase upsert error: {e}")

    print(
        "[LankaLens Seed] Database seed pipeline prepared in-memory dataset successfully."
    )
    return SEED_DATASETS


if __name__ == "__main__":
    seed_database()
